# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 300
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', disabled: true
  
  (1..2).each do |i|
    config.vm.define "ubuntu#{i}" do |node|
      # https://portal.cloud.hashicorp.com/vagrant/discover/ubuntu/jammy64
      node.vm.box = "ubuntu/jammy64"
      node.vm.box_version = "20241002.0.0"
      node.vm.hostname = "ubuntu#{i}"
      node.vm.network "private_network", ip: "192.168.56.#{10+i}"
      node.vm.provider :virtualbox do |vb|
        vb.memory = 512
        vb.cpus = 1
        vb.linked_clone = true
        # https://github.com/joelhandwell/ubuntu_vagrant_boxes/issues/1#issuecomment-292370353
        vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]

        # https://stackoverflow.com/a/54481502
        vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
      end
    end
  end
  
  config.vm.define "macos" do |node|
    # https://portal.cloud.hashicorp.com/vagrant/discover/jhcook/macos-sierra
    node.vm.box = "jhcook/macos-sierra"
    node.vm.box_version = "10.12.6"
    node.vm.hostname = "macos"
    node.vm.network "private_network", ip: "192.168.56.13"
    node.vm.provider :virtualbox do |vb|
      vb.memory = 2048
      vb.cpus = 2
      # https://stackoverflow.com/a/78589151
      vb.customize ['setextradata', :id, 'VBoxInternal/Devices/smc/0/Config/GetKeyFromRealSMC', '0']
    end
    
    node.vm.provision "shell", inline: <<-SHELL
      # Install Command Line Tools
      # https://apple.stackexchange.com/a/195963
      touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress;
      PROD=$(softwareupdate -l |
        grep "\*.*Command Line" |
        head -n 1 | awk -F"*" '{print $2}' |
        sed -e 's/^ *//' |
        tr -d '\n')
      softwareupdate -i "$PROD" --verbose
      rm /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress

      # Install Homebrew
      # https://docs.brew.sh/Installation#unattended-installation
      # https://github.com/Homebrew/install?tab=readme-ov-file#install-homebrew-on-macos-or-linux
      NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      # Install pyenv
      # https://github.com/pyenv/pyenv/wiki#suggested-build-environment
      brew install readline xz
      curl https://pyenv.run | bash

      # Install python
      $HOME/.pyenv/bin/pyenv install 3.12
      $HOME/.pyenv/bin/pyenv global 3.12
    SHELL
  end
end