# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Use ubuntu/jammy64 box
  # https://portal.cloud.hashicorp.com/vagrant/discover/ubuntu/jammy64
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_version = "20241002.0.0"
  config.vm.boot_timeout = 300
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', disabled: true
  
  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 2
    v.linked_clone = true
    # https://github.com/joelhandwell/ubuntu_vagrant_boxes/issues/1#issuecomment-292370353
    v.customize ["modifyvm", :id, "--uartmode1", "disconnected"]

    # https://stackoverflow.com/a/54481502
    v.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end

  config.vm.define "ubuntu" do |node|
    node.vm.hostname = "ubuntu"
    node.vm.network "private_network", ip: "192.168.56.11"
  end

end