# https://game.ci/docs/github/deployment/ios#5-configure-fastlane-to-build

match_org, match_repo = (ENV["MATCH_REPOSITORY"]||"").split("/")
git_server_domain = ENV["GIT_SERVER_DOMAIN"]
keychain_name = "fastlane_tmp_keychain"
keychain_password = SecureRandom.base64

def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  # https://docs.fastlane.tools/actions/create_keychain/
  # https://docs.fastlane.tools/actions/setup_ci/
  create_keychain(
    name: name,
    password: password,
    default_keychain: true,
    unlock: true,
    timeout: 0,
    add_to_search_list: true,
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  before_all do |lane|
    if is_ci
      ensure_temp_keychain(keychain_name, keychain_password)
    end

    app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV['APPSTORE_P8']
    )
  end
  
  after_all do |lane|
    if is_ci
      delete_temp_keychain(keychain_name)
    end
  end

  desc "Sync codesigning certificates"
  lane :sync_certificates do
    # https://docs.fastlane.tools/actions/match/#parameters
    match(
      type: "appstore",
      readonly: is_ci,
      storage_mode: "git",
      git_url: "ssh://git@#{git_server_domain}:2222/#{match_org}/#{match_repo}.git",
      git_branch: "main",
      app_identifier: ENV["IOS_BUNDLE_ID"],
      keychain_name: keychain_name,
      keychain_password: keychain_password,
    )
  end

  desc "Deliver a new Release build to the App Store"
  lane :release do
    build
    upload_to_app_store
  end

  desc "Deliver a new Beta build to Apple TestFlight"
  lane :beta do
    # Missing Export Compliance can also be set through Deliverfile
    update_info_plist(
      xcodeproj: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj",
      plist_path: 'Info.plist',
      block: proc do |plist|
        plist['ITSAppUsesNonExemptEncryption'] = false
      end
    )
    build
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  desc "Create .ipa"
  lane :build do
    sync_certificates

    # Unity has specific requirements around codesigning that we have to handle
    # See https://github.com/fastlane/fastlane/discussions/17458 for context
    update_code_signing_settings(
      use_automatic_signing: true,
      path: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj"
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: ENV["sigh_#{ENV['IOS_BUNDLE_ID']}_appstore_team-id"],
      code_sign_identity: 'iPhone Distribution',
      targets: 'Unity-iPhone',
      path: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj",
      profile_name: ENV["sigh_#{ENV['IOS_BUNDLE_ID']}_appstore_profile-name"],
      profile_uuid: ENV["sigh_#{ENV['IOS_BUNDLE_ID']}_appstore"]
    )

    build_app( #alias: gym
      project: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj",
      scheme: 'Unity-iPhone',
      xcargs: '-allowProvisioningUpdates'
    )
  end

end