name: iOS Build with Match
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ios-build:
    runs-on: macos-latest
    steps:
      # Setup Ruby environment
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add Known Hosts
        run: |
          ssh-keyscan -H ${{ env.GIT_SERVER_DOMAIN }} >> ~/.ssh/known_hosts

      - name: Sync certificates
        run: bundle exec fastlane ios sync_development
        env:
          APPLE_DEVELOPER_USERNAME: ${{ secrets.APPLE_DEVELOPER_USERNAME }}
          APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_P8: ${{ secrets.APPSTORE_P8 }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          MATCH_REPO: ${{ secrets.MATCH_REPO }}
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}