# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Use ubuntu/jammy64 box
  # https://portal.cloud.hashicorp.com/vagrant/discover/ubuntu/jammy64
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_version = "20241002.0.0"
  config.vm.boot_timeout = 300
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', disabled: true
  
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.cpus = 1
    v.linked_clone = true
    # https://gist.github.com/travelhawk/b9c1b6b7a9cd35cf3898fcb33cdae72d#verr_path_not_found-when-using-vagrant-up
    # https://github.com/joelhandwell/ubuntu_vagrant_boxes/issues/1#issuecomment-292370353
    v.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
    
    # https://stackoverflow.com/a/54481502
    v.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end

  (1..2).each do |i|
    config.vm.define "ubuntu#{i}" do |node|
      node.vm.hostname = "ubuntu#{i}"
      node.vm.network "private_network", ip: "192.168.56.#{10+i}"
    end
  end

  (1..2).each do |i|
    config.vm.define "ubuntu#{2+i}" do |node|
      node.vm.hostname = "ubuntu#{2+i}"
      node.vm.network "private_network", ip: "192.168.57.#{10+i}"
    end
  end

  # Disable automatic box update checks to avoid issues
  config.vm.box_check_update = false
end