# Example workflow using actions/checkout for repository access
name: CI with webfactory/ssh-agent and actions/checkout
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_SERVER_DOMAIN: forgejo.yourdomain
      SSH_CONFIG_PATH: ${{ runner.temp }}/.ssh/config
      SSH_KEY_PATH: ${{ runner.temp }}/.ssh/deploy_key
      SSH_KNOWN_HOSTS_PATH: ${{ runner.temp }}/.ssh/known_hosts
    steps:
      - uses: actions/checkout@v4
      
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      # Configure Git Server
      - name: Configure Git Server
        run: |
          # Create SSH directory in temp
          SSH_DIR="${{ runner.temp }}/.ssh"
          mkdir -p "$SSH_DIR"
          chmod 700 "$SSH_DIR"
          
          # Create SSH config
          cat > "$SSH_CONFIG_PATH" << EOF
          Host $GIT_SERVER_DOMAIN
            UserKnownHostsFile $SSH_KNOWN_HOSTS_PATH
            StrictHostKeyChecking yes
          EOF
          chmod 600 "$SSH_CONFIG_PATH"
          
          # Add known hosts
          ssh-keyscan -t rsa,ed25519 $GIT_SERVER_DOMAIN > "$SSH_KNOWN_HOSTS_PATH"
          chmod 644 "$SSH_KNOWN_HOSTS_PATH"
          
          # Test SSH connection
          ssh -F "$SSH_CONFIG_PATH" -T "git@$GIT_SERVER_DOMAIN" || true
      
      # Clone private repository using actions/checkout
      - name: Clone Private Repository
        uses: actions/checkout@v4
        with:
          repository: owner/private-repo
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          github-server-url: "https://${{ env.GIT_SERVER_DOMAIN }}"
      
      # Cleanup
      - name: Cleanup
        if: always()
        run: rm -rf "${{ runner.temp }}/.ssh"
