# Example workflow using manual SSH setup for repository access
name: Manual SSH Setup with Expect
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ssh-setup:
    runs-on: ubuntu-latest
    env:
      GIT_SERVER_DOMAIN: forgejo.yourdomain
      GIT_SERVER_SSH_PORT: 22
      SSH_CONFIG_PATH: ${{ runner.temp }}/.ssh/config
      SSH_KEY_PATH: ${{ runner.temp }}/.ssh/deploy_key
      SSH_KNOWN_HOSTS_PATH: ${{ runner.temp }}/.ssh/known_hosts
    steps:
      # Install expect for handling passphrase
      - name: Install expect
        run: |
          sudo apt-get update
          sudo apt-get install -y expect

      # Setup SSH with expect for passphrase
      - name: Setup SSH with expect
        env:
          SSH_KEY: ${{ secrets.DEPLOY_KEY }}
          SSH_KEY_PASSPHRASE: ${{ secrets.SSH_KEY_PASSPHRASE }}
        run: |
          # Create SSH directory in temp
          SSH_DIR="${{ runner.temp }}/.ssh"
          mkdir -p "$SSH_DIR"
          chmod 700 "$SSH_DIR"
          
          # Save private key to file
          echo "$SSH_KEY" > "$SSH_KEY_PATH"
          chmod 600 "$SSH_KEY_PATH"
          
          # Create SSH config
          cat > "$SSH_CONFIG_PATH" << EOF
          Host $GIT_SERVER_DOMAIN
            IdentityFile $SSH_KEY_PATH
            UserKnownHostsFile $SSH_KNOWN_HOSTS_PATH
            StrictHostKeyChecking yes
            Port $GIT_SERVER_SSH_PORT
          EOF
          chmod 600 "$SSH_CONFIG_PATH"
          
          # Add known hosts
          ssh-keyscan -t rsa,ed25519 -p $GIT_SERVER_SSH_PORT $GIT_SERVER_DOMAIN > "$SSH_KNOWN_HOSTS_PATH"
          chmod 644 "$SSH_KNOWN_HOSTS_PATH"
          
          # Create expect script for adding key with passphrase
          cat > "${{ runner.temp }}/add-key.exp" << 'EOF'
          #!/usr/bin/expect -f
          
          # Set timeout
          set timeout 10
          
          # Start ssh-add with specific key file
          spawn ssh-add $env(SSH_KEY_PATH)
          
          # Handle passphrase prompt
          expect {
              "Enter passphrase" {
                  send "$env(SSH_KEY_PASSPHRASE)\r"
                  exp_continue
              }
              timeout {
                  puts "Timeout waiting for passphrase prompt"
                  exit 1
              }
              eof {
                  catch wait result
                  exit [lindex $result 3]
              }
          }
          interact
          EOF
          
          chmod +x "${{ runner.temp }}/add-key.exp"
          
          # Start ssh-agent
          eval "$(ssh-agent -s)"
          
          # Run expect script
          "${{ runner.temp }}/add-key.exp"
          
          # Test SSH connection
          ssh -F "$SSH_CONFIG_PATH" -T "git@$GIT_SERVER_DOMAIN" || true

      # Clone private repository
      - name: Clone private repository
        env:
          GIT_SSH_COMMAND: "ssh -F $SSH_CONFIG_PATH"
        run: |
          git clone "git@$GIT_SERVER_DOMAIN:owner/private-repo.git" private-repo
          cd private-repo && git status

      # Cleanup sensitive files
      - name: Cleanup
        if: always()
        run: |
          rm -rf "${{ runner.temp }}/.ssh"
          rm -f "${{ runner.temp }}/add-key.exp"
          eval "$(ssh-agent -k)" || true
