#!/bin/bash

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - bash)"

# Beucase "curl -fsSL https://fnm.vercel.app/install | bash" use brew to install fnm
# fnm is installed in brew path, mean fnm command will already on PATH
# https://github.com/Schniz/fnm?tab=readme-ov-file#upgrade
if command -v fnm &>/dev/null; then
  # https://github.com/Schniz/fnm?tab=readme-ov-file#shell-setup
  # Runner execute command without shell, and `fnm env` will failed if there is no shell
  # Explicitly tell fnm generate env for bash
  eval "$(fnm env --shell bash)"
fi