name: Unity UWP Build 🎮

on:
  push:
  pull_request:

jobs:
  build:
    name: Build Unity UWP Project
    runs-on: windows-latest
    
    strategy:
      matrix:
        unityProjectPath:
          - test-project
        unityVersions:
          - 2019.4.31f1
        targetPlatforms:
          - WSAPlayer # Build for UWP
        platform: [x86, x64, ARM, ARM64]
        configuration: [Debug, Release]
    
    env:
      APP_NAME: TestApp
      CERT_PATH: cert.pfx
    
    steps:
      # Checkout
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      # Cache
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.unityProjectPath }}/Library
          key: Library-${{ matrix.unityProjectPath }}-${{ hashFiles('${{ matrix.unityProjectPath }}/Assets/**', '${{ matrix.unityProjectPath }}/Packages/**', '${{ matrix.unityProjectPath }}/ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.unityProjectPath }}-

      # Test
      - name: Run Unity Tests
        uses: https://github.com/game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.unityProjectPath }}
          testMode: all
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport'
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build Unity Project
      - name: Build Unity Project
        uses: https://github.com/game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          buildName: UWPBuild
          projectPath: ${{ matrix.unityProjectPath }}
          unityVersion: ${{ matrix.unityVersions }}
          targetPlatform: ${{ matrix.targetPlatforms }}
          customParameters: -profile SomeProfile -someBoolean -someValue exampleValue

      # Setup Build Tools
      - name: Setup MSBuild
        uses: https://github.com/microsoft/setup-msbuild@v2

      - name: Setup .NET
        uses: https://github.com/actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      # Decode Certificate for Store Submission
      - name: Decode Signing Certificate
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.CERT_BASE64_ENCODED }}")
          [IO.File]::WriteAllBytes("$env:CERT_PATH", $pfx_cert_byte)

      # Build UWP Solution
      - name: Build UWP App
        env:
          SOLUTION_PATH: build/${{ env.APP_NAME }}.sln
          PACKAGE_PATH: build/AppPackages/${{ env.APP_NAME }}
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
        run: |
          msbuild $env:SOLUTION_PATH `
          /p:Platform=${{ matrix.platform }} `
          /p:Configuration=${{ matrix.configuration }} `
          /p:AppxBundlePlatforms="${{ matrix.platform }}" `
          /p:AppxPackageDir="$env:PACKAGE_PATH" `
          /p:AppxBundle=Always `
          /p:UapAppxPackageBuildMode=StoreUpload `
          /p:GenerateAppxPackageOnBuild=true `
          ${{ github.event_name != 'pull_request' && format('/p:PackageCertificateKeyFile={0} /p:PackageCertificatePassword="$env:CERT_PASSWORD"', $env.CERT_PATH) || '' }}

      # Cleanup Certificate
      - name: Remove Certificate
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          Remove-Item -Path "$env:CERT_PATH"

      # Upload Build Artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        env:
          PACKAGE_PATH: build/AppPackages/${{ env.APP_NAME }}
        with:
          name: MSIX-${{ matrix.unityProjectPath }}-${{ matrix.platform }}-${{ matrix.configuration }}
          path: ${{ env.PACKAGE_PATH }}
          retention-days: 14
