source "https://rubygems.org"

gem "fastlane"
# The published gem is missing necessary changes, so we need to link directly to the git repo
gem 'fastlane-plugin-github_action', git: "https://github.com/joshdholtz/fastlane-plugin-github_action" 