name: Generate iOS Certs

on:
  workflow_dispatch:

jobs:
  generate_certs:
    runs-on: macos-latest
    env:
      GIT_SERVER_SSH_PORT: 2222
      SSH_KEY_NAME: match-deploy-key
      SSH_AUTH_SOCK: /tmp/ssh-agent.sock
    steps:
      # Require to fetch fastlane configuration files
      - uses: actions/checkout@v4

      # Make sure that the operating system has libyaml-0 and libgmp installed
      # On MacOS: brew install libyaml gmp
      # Need to setup cache directory on self-hosted runners
      # Reference: https://github.com/ruby/setup-ruby?tab=readme-ov-file#using-self-hosted-runners
      - uses: https://github.com/ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      # https://stackoverflow.com/a/11385736
      - name: Setup GIT_SERVER_DOMAIN 
        run: |
          echo "GIT_SERVER_DOMAIN=$(echo $GITHUB_SERVER_URL | awk -F[/:] '{print $4}')" >> $GITHUB_ENV

      - name: Install SSH Key
        uses: https://github.com/shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          name: ${{ env.SSH_KEY_NAME }}
          # https://github.com/shimataro/ssh-key-action?tab=readme-ov-file#i-want-to-omit-known_hosts
          known_hosts: unnecessary
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
          config: |
            Host ${{ env.GIT_SERVER_DOMAIN }}
              Port ${{ env.GIT_SERVER_SSH_PORT }}
              StrictHostKeyChecking yes

      - name: Add SSH Known Hosts
        run: |
          ssh-keyscan -p ${{ env.GIT_SERVER_SSH_PORT }} -H ${{ env.GIT_SERVER_DOMAIN }} >> "${HOME}/.ssh/known_hosts"

      - name: Build iOS
        shell: bash
        run: |
          bundle exec fastlane ios sync_certificates
        env:
          # https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8

          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_P8: ${{ secrets.APPSTORE_P8 }}

          IOS_BUNDLE_ID: ${{ secrets.IOS_BUNDLE_ID }}

          MATCH_REPOSITORY: ${{ secrets.MATCH_REPOSITORY }}
          MATCH_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          MATCH_PASSWORD: ${{ secrets.SSH_KEY_PASSPHRASE }}
          MATCH_GIT_PRIVATE_KEY: ${{ env.HOME }}/.ssh/${{ env.SSH_KEY_NAME }}