name: Generate iOS Certs

on:
  workflow_dispatch:

jobs:
  generate_certs:
    runs-on: macos-latest
    env:
      GIT_SERVER_SSH_PORT: 2222
      SSH_KEY_NAME: match-deploy-key
      SSH_AUTH_SOCK: /tmp/ssh-agent.sock

    steps:
      # Require to fetch fastlane configuration files
      - uses: actions/checkout@v4

      # Make sure that the operating system has libyaml-0 and libgmp installed
      # On MacOS: brew install libyaml gmp
      # Need to setup cache directory on self-hosted runners
      # Reference: https://github.com/ruby/setup-ruby?tab=readme-ov-file#using-self-hosted-runners
      - uses: https://github.com/ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      # https://stackoverflow.com/a/11385736
      - name: Setup GIT_SERVER_DOMAIN 
        run: |
          echo "GIT_SERVER_DOMAIN=$(echo $GITHUB_SERVER_URL | awk -F[/:] '{print $4}')" >> $GITHUB_ENV

      - name: Install SSH Key
        uses: https://github.com/shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          name: ${{ env.SSH_KEY_NAME }}
          # https://github.com/shimataro/ssh-key-action?tab=readme-ov-file#i-want-to-omit-known_hosts
          known_hosts: unnecessary
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
          config: |
            Host ${{ env.GIT_SERVER_DOMAIN }}
              Port ${{ env.GIT_SERVER_SSH_PORT }}
              StrictHostKeyChecking yes

      - name: Add SSH Known Hosts
        run: |
          ssh-keyscan -p ${{ env.GIT_SERVER_SSH_PORT }} -H ${{ env.GIT_SERVER_DOMAIN }} >> "${HOME}/.ssh/known_hosts"

      - name: Start ssh-agent
        run: |
          eval "$(ssh-agent -s)"
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
          echo "SSH_AGENT_PID=$SSH_AGENT_PID" >> $GITHUB_ENV

      - name: Install expect to add key to ssh-agent with passphrase
        run: |
          # Install expect
          sudo apt-get update
          sudo apt-get install -y expect

      - name: Add Passphrase to ssh-agent
        env:
          SSH_KEY_PASSPHRASE: ${{ secrets.SSH_KEY_PASSPHRASE }}
        run: |
          # Create expect script for adding key with passphrase
          add_key_tmp=mktemp
          cat > "$add_key_tmp" << 'EOF'
          #!/usr/bin/expect -f
          set timeout 10
          spawn ssh-add "$env(HOME)/.ssh/${{ env.SSH_KEY_NAME }}"
          expect "Enter passphrase"
          send "$env(SSH_KEY_PASSPHRASE)\r"
          expect eof
          EOF
          chmod 700 "$add_key_tmp"
          
          # Run expect script
          expect "$add_key_tmp"
          rm -f "$add_key_tmp"
          
          # Test SSH connection (success message expected)
          ssh -T "git@$GIT_SERVER_DOMAIN" || true

      - name: Generate iOS Certs
        shell: bash
        run: |
          bundle exec fastlane ios sync_certificates
        env:
          # https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8

          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_P8: ${{ secrets.APPSTORE_P8 }}

          IOS_BUNDLE_ID: ${{ secrets.IOS_BUNDLE_ID }}

          MATCH_REPOSITORY: ${{ secrets.MATCH_REPOSITORY }}
          # Match password use for encrypt and decrypt files in git repository
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      - name: Cleanup ssh-agent
        if: always()
        run: |
          eval "$(ssh-agent -k)" || true