name: Test MacOS Runner Setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-native:
    name: Test Native MacOS Commands
    runs-on: macos-sonoma-m1
    steps:
      - uses: actions/checkout@v4
      
      - name: Test Basic Commands
        run: |
          uname -a
          sw_vers
          
      - name: Test Environment
        run: |
          echo "HOME: $HOME"
          echo "PATH: $PATH"
          env
          
      - name: Test File Operations
        run: |
          touch test.txt
          echo "Hello from MacOS Runner" > test.txt
          cat test.txt
          ls -la

  test-docker:
    name: Test Docker Functionality
    runs-on: macos-sonoma-m1
    steps:
      - uses: actions/checkout@v4
      
      - name: Test Docker Installation
        run: |
          docker --version
          docker info
          
      - name: Test Docker Pull and Run
        run: |
          # Pull test image
          docker pull hello-world
          docker images
          
          # Run test container
          docker run hello-world
          docker ps -a
          
      - name: Test Multi-architecture Support
        run: |
          echo "Testing ARM64 container:"
          docker run --rm --platform linux/arm64 alpine uname -m
          docker run --rm --platform linux/arm64 alpine arch
          
          echo "Testing x86_64 container:"
          docker run --rm --platform linux/amd64 alpine uname -m
          docker run --rm --platform linux/amd64 alpine arch
          
          echo "Testing native platform container:"
          docker run --rm alpine uname -m
          docker run --rm alpine arch
          
      - name: Test Docker Build
        run: |
          # Create multi-arch test Dockerfile
          cat > Dockerfile << 'EOF'
          FROM alpine:latest
          RUN uname -m > /platform.txt && \
              echo "Architecture: $(arch)" >> /platform.txt
          CMD ["cat", "/platform.txt"]
          EOF
          
          # Build and test image for both architectures
          echo "Building and testing ARM64 image:"
          docker build --platform linux/arm64 -t test-image:arm64 .
          docker run --rm --platform linux/arm64 test-image:arm64
          
          echo "Building and testing AMD64 image:"
          docker build --platform linux/amd64 -t test-image:amd64 .
          docker run --rm --platform linux/amd64 test-image:amd64
          
          echo "Building and testing native image:"
          docker build -t test-image:native .
          docker run --rm test-image:native
          
      - name: Cleanup Docker Resources
        if: always()
        run: |
          echo "Cleaning up test containers..."
          # Only remove containers with our test images
          docker ps -a --filter "ancestor=test-image:arm64" -q | xargs docker rm -f 2>/dev/null || true
          docker ps -a --filter "ancestor=test-image:amd64" -q | xargs docker rm -f 2>/dev/null || true
          docker ps -a --filter "ancestor=test-image:native" -q | xargs docker rm -f 2>/dev/null || true
          
          echo "Cleaning up test images..."
          # Only remove our test images
          docker rmi -f test-image:arm64 || true
          docker rmi -f test-image:amd64 || true
          docker rmi -f test-image:native || true
          docker rmi -f hello-world || true
          docker rmi -f alpine:latest || true
          
          echo "Cleaning up dangling images..."
          docker image prune -f
          
          echo "Verifying cleanup..."
          docker ps -a
          docker images

  test-complex:
    name: Test Complex Workflow
    runs-on: macos-sonoma-m1
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        run: |
          python -V
          python -m pip install --upgrade pip
          
      - name: Create Python Script
        run: |
          cat > test.py << 'EOF'
          import os
          import sys
          import platform
          
          print("Python Version:", sys.version)
          print("Platform Info:", platform.platform())
          print("Current Directory:", os.getcwd())
          
          # Create and read a file
          with open('output.txt', 'w') as f:
              f.write("Test successful!")
          
          with open('output.txt', 'r') as f:
              print("File contents:", f.read())
          EOF
          
      - name: Run Python Script
        run: python test.py
        
      - name: Test File Persistence
        run: |
          ls -la
          cat output.txt