# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # General Vagrant VM configuration.
  config.vm.box = "ubuntu/jammy64"
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.cpus = 1
    v.linked_clone = true
    # https://github.com/joelhandwell/ubuntu_vagrant_boxes/issues/1#issuecomment-292370353
    v.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end

  # Define two Ubuntu test machines
  (1..2).each do |i|
    config.vm.define "ubuntu#{i}" do |node|
      node.vm.hostname = "ubuntu#{i}"
      node.vm.network "private_network", ip: "192.168.56.#{10+i}"

      # Setup test environment
      node.vm.provision "shell", inline: <<-SHELL
        # python and unattended-upgrades are installed by default in "ubuntu/jammy64" image

        # Update package list
        apt-get update

        # Install nodejs to test check-updates
        # Nodejs version 12 will be installed with default DEB repository in "ubuntu/jammy64" image
        apt-get install nodejs -y
        
        # Update nodejs DEB repository
        # https://deb.nodesource.com/
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash - 

        # Simulate packages requiring reboot
        echo "Set up a reboot requirement"
        touch /var/run/reboot-required
        echo "linux-image-generic" > /var/run/reboot-required.pkgs
        echo "linux-headers-generic" >> /var/run/reboot-required.pkgs
        echo "dbus" >> /var/run/reboot-required.pkgs
      SHELL
    end
  end

  # Disable automatic box update checks to avoid issues
  config.vm.box_check_update = false
end