# - Windows Server Core: https://hub.docker.com/r/microsoft/windows-servercore
# - Windows SDK Server Core: https://github.com/dotnet/dotnet-docker/blob/main/README.sdk.md
# - Docker Windows Server Core Dockerfile: https://github.com/docker-library/docker/blob/master/27/windows/windowsservercore-ltsc2022/Dockerfile
# - GameCI Docker Images: https://hub.docker.com/r/unityci/hub/tags

ARG WINDOWS_IMAGE="mcr.microsoft.com/windows/servercore:ltsc2022"
FROM ${WINDOWS_IMAGE}