# Example workflow for containerized runners (GitHub-hosted or containerized self-hosted)
name: Checkout with Passphrase
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  checkout:
    # This workflow is designed for containerized environments
    runs-on: ubuntu-latest
    env:
      GIT_SERVER_SSH_PORT: 2222
      SSH_KEY_NAME: deploy-key
      SSH_AUTH_SOCK: /tmp/ssh-agent.sock

    steps:
      - name: Setup GIT_SERVER_DOMAIN
        # https://stackoverflow.com/a/11385736
        run: |
          echo "GIT_SERVER_DOMAIN=$(echo $GITHUB_SERVER_URL | awk -F[/:] '{print $4}')" >> $GITHUB_ENV

      - name: Install SSH Key
        uses: https://github.com/shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          name: ${{ env.SSH_KEY_NAME }}
          # https://github.com/shimataro/ssh-key-action?tab=readme-ov-file#i-want-to-omit-known_hosts
          known_hosts: unnecessary
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
          config: |
            Host ${{ env.GIT_SERVER_DOMAIN }}
              Port ${{ env.GIT_SERVER_SSH_PORT }}
              StrictHostKeyChecking yes
              
      - name: Add SSH Known Hosts
        run: |
          ssh-keyscan -p ${{ env.GIT_SERVER_SSH_PORT }} -H ${{ env.GIT_SERVER_DOMAIN }} >> "${HOME}/.ssh/known_hosts"

      - name: Start ssh-agent
        run: |
          eval "$(ssh-agent -s)"
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
          echo "SSH_AGENT_PID=$SSH_AGENT_PID" >> $GITHUB_ENV

      - name: Install expect to add key to ssh-agent with passphrase
        run: |
          # Install expect
          sudo apt-get update
          sudo apt-get install -y expect

      - name: Add Passphrase to ssh-agent
        env:
          SSH_KEY_PASSPHRASE: ${{ secrets.SSH_KEY_PASSPHRASE }}
        run: |
          # Create expect script for adding key with passphrase
          add_key_tmp=mktemp
          cat > "$add_key_tmp" << 'EOF'
          #!/usr/bin/expect -f
          set timeout 10
          spawn ssh-add "$env(HOME)/.ssh/${{ env.SSH_KEY_NAME }}"
          expect "Enter passphrase"
          send "$env(SSH_KEY_PASSPHRASE)\r"
          expect eof
          EOF
          chmod 700 "$add_key_tmp"
          
          # Run expect script
          expect "$add_key_tmp"
          rm -f "$add_key_tmp"
          
          # Test SSH connection (success message expected)
          ssh -T "git@$GIT_SERVER_DOMAIN" || true
      
      - name: Clone remote private Repository
        uses: https://github.com/actions/checkout@v4
        with:
          repository: owner/private-repo
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          ssh-known-hosts: ${{ env.GIT_SERVER_DOMAIN }}
      
      - name: Cleanup
        if: always()
        run: |
          eval "$(ssh-agent -k)" || true
