# Example workflow for containerized runners (GitHub-hosted or containerized self-hosted)
name: Checkout with SSH Agent
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  checkout:
    # This workflow is designed for containerized environments
    runs-on: ubuntu-latest
    env:
      GIT_SERVER_SSH_PORT: 2222
    steps:
      - name: Setup GIT_SERVER_DOMAIN
        # https://stackoverflow.com/a/11385736
        run: |
          echo "GIT_SERVER_DOMAIN=$(echo $GITHUB_SERVER_URL | awk -F[/:] '{print $4}')" >> $GITHUB_ENV

      - name: Install SSH Key
        uses: https://github.com/shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          name: ${{ env.SSH_KEY_NAME }}
          # https://github.com/shimataro/ssh-key-action?tab=readme-ov-file#i-want-to-omit-known_hosts
          known_hosts: unnecessary
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
          config: |
            Host ${{ env.GIT_SERVER_DOMAIN }}
              Port ${{ env.GIT_SERVER_SSH_PORT }}
              StrictHostKeyChecking yes

      - name: Add SSH Known Hosts
        run: |
          ssh-keyscan -p ${{ env.GIT_SERVER_SSH_PORT }} -H ${{ env.GIT_SERVER_DOMAIN }} >> "${HOME}/.ssh/known_hosts"

      - name: Setup SSH Agent 
        uses: https://github.com/shimataro/webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      
      - name: Test SSH Connection
        run: |
          # Test SSH connection (success message expected)
          ssh -T "git@$GIT_SERVER_DOMAIN" || true
      
      - name: Clone remote private Repository
        uses: https://github.com/actions/checkout@v4
        with:
          repository: owner/private-repo
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          ssh-known-hosts: ${{ env.GIT_SERVER_DOMAIN }}
      
      # Cleanup
      - name: Cleanup
        if: always()
        run: rm -rf "~/.ssh"
